export const translations = {
  en: {
    title: "MANUSHI Sh.P.K",
    subtitle: "Currency Exchange - Tirana",
    from: "From",
    to: "To",
    rate: "rate",
    findUs: "Find Us",
    address: "Blv. Zogu I, Te Sigal, K. I",
    city: "1000 — Tiranë, Albania",
    whoWeAre: "Who We Are",
    aboutText: "Manushi Sh.P.K has been serving the people of Tirana with fast, reliable and transparent currency exchange. No hidden fees, no surprises — just honest rates and professional service every time you walk through our door.",
    commission: "Commission Fees",
    currencies: "Currencies Available",
    updates: "Rate Updates",
  },
  al: {
    title: "MANUSHI Sh.P.K",
    subtitle: "Këmbim Valutor - Tiranë",
    from: "Nga",
    to: "Në",
    rate: "kurs",
    findUs: "Na Gjeni",
    address: "Blv. Zogu I, Te Sigal, K. I",
    city: "1000 — Tiranë, Shqipëri",
    whoWeAre: "Kush Jemi Ne",
    aboutText: "Manushi Sh.P.K i shërben popullit të Tiranës me këmbim valutor të shpejtë, të besueshëm dhe transparent. Pa komisione, pa surpriza — vetëm kurse të ndershme dhe shërbim profesional.",
    commission: "Pa Komision",
    currencies: "Valuta të Disponueshme",
    updates: "Përditësim Kursesh",
  },
  it: {
    title: "MANUSHI Sh.P.K",
    subtitle: "Cambio Valuta - Tirana",
    from: "Da",
    to: "A",
    rate: "tasso",
    findUs: "Trovaci",
    address: "Blv. Zogu I, Te Sigal, K. I",
    city: "1000 — Tirana, Albania",
    whoWeAre: "Chi Siamo",
    aboutText: "Manushi Sh.P.K serve i cittadini di Tirana con un cambio valuta veloce, affidabile e trasparente. Nessuna commissione, nessuna sorpresa — solo tassi onesti e servizio professionale.",
    commission: "Zero Commissioni",
    currencies: "Valute Disponibili",
    updates: "Aggiornamento Tassi",
  },
}